repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: mixed-line-ending
        args: [ '--fix=lf' ]
## PY
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.4
    hooks:
      - id: ruff-check
        args: [ '--fix' ]
        files: ^ipp26-project-templates/python/int/src/interpreter/
      - id: ruff-format
        files: ^ipp26-project-templates/python/int/src/interpreter/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        pass_filenames: false
        args: [ '--strict', '--explicit-package-bases', 'ipp26-project-templates/python/int/src/']
        additional_dependencies: [
          "pydantic[mypy]~=2.12.5",
          "pydantic-xml[lxml]~=2.19.0",
          "types-lxml>=2026.2.16",
        ]
## TS
  - repo: local
    hooks:
      - id: ts-lint
        name: ESLint (Tester)
        pass_filenames: false
        entry: npm --prefix ipp26-project-templates/typescript/tester/ run lint
        language: system
        files: ^ipp26-project-templates/typescript/tester/.*\.ts$

      - id: ts-format
        name: Prettier (Tester)
        pass_filenames: false
        entry: npm --prefix ipp26-project-templates/typescript/tester run format
        language: system
        files: ^ipp26-project-templates/typescript/tester/.*\.ts$

      - id: ts-type-check
        name: TypeScript Type Check
        pass_filenames: false
        entry: npm --prefix ipp26-project-templates/typescript/tester/ run typecheck
        language: system
        files: ^ipp26-project-templates/typescript/tester/.*\.ts$
