"""
This module defines the internal memory representation of SOL26 objects.
"""


class SolObject:
    def identicalTo(self): ...
    def equalTo(self): ...
    def asString(self): ...
    def isNumber(self): ...
    def isString(self): ...
    def isBlock(self): ...
    def isNil(self): ...
    def isBoolean(self): ...


class SolNil(SolObject): ...


class SolInteger(SolObject): ...


class SolString(SolObject): ...


class SolBlock(SolObject): ...


class SolBoolean(SolObject): ...


class SolTrue(SolBoolean): ...


class SolFalse(SolBoolean): ...
